// ============================================
// Mock Parking Lots Data
// ============================================

import { ParkingLot } from '../types';

export const mockParkingLots: ParkingLot[] = [
  {
    id: 'lot-001',
    name: 'Al Andalus Mall Parking',
    address: 'King Fahd Road, Riyadh',
    location: { lat: 24.7233, lng: 46.6753 },
    totalSlots: 450,
    availableSlots: 78,
    pricePerHour: 15,
    pricePerDay: 60,
    rating: 4.8,
    reviewCount: 342,
    photoUrls: [
      'https://via.placeholder.com/400x300?text=Al+Andalus+Mall',
    ],
    amenities: {
      covered: true,
      evCharging: true,
      disabledAccess: true,
      cctv: true,
      valet: true,
      carWash: false,
    },
    hours: {
      is24Hours: true,
      closedDays: [],
    },
    distanceMeters: 1200,
  },
  {
    id: 'lot-002',
    name: 'Riyadh Gallery Parking',
    address: 'Olaya Street, Riyadh',
    location: { lat: 24.7645, lng: 46.6734 },
    totalSlots: 300,
    availableSlots: 45,
    pricePerHour: 12,
    pricePerDay: 45,
    rating: 4.5,
    reviewCount: 215,
    photoUrls: [
      'https://via.placeholder.com/400x300?text=Riyadh+Gallery',
    ],
    amenities: {
      covered: true,
      evCharging: false,
      disabledAccess: true,
      cctv: true,
      valet: false,
      carWash: true,
    },
    hours: {
      is24Hours: false,
      openTime: '08:00',
      closeTime: '23:00',
      closedDays: [],
    },
    distanceMeters: 2500,
  },
  {
    id: 'lot-003',
    name: 'Faisaliah Tower Parking',
    address: 'Faisaliah, Riyadh',
    location: { lat: 24.7625, lng: 46.7125 },
    totalSlots: 600,
    availableSlots: 156,
    pricePerHour: 20,
    pricePerDay: 75,
    rating: 4.9,
    reviewCount: 521,
    photoUrls: [
      'https://via.placeholder.com/400x300?text=Faisaliah+Tower',
    ],
    amenities: {
      covered: true,
      evCharging: true,
      disabledAccess: true,
      cctv: true,
      valet: true,
      carWash: true,
    },
    hours: {
      is24Hours: true,
      closedDays: [],
    },
    distanceMeters: 3100,
  },
  {
    id: 'lot-004',
    name: 'Centria Mall Parking',
    address: 'Northern Ring Road, Riyadh',
    location: { lat: 24.8456, lng: 46.7234 },
    totalSlots: 250,
    availableSlots: 5,
    pricePerHour: 10,
    pricePerDay: 35,
    rating: 4.2,
    reviewCount: 128,
    photoUrls: [
      'https://via.placeholder.com/400x300?text=Centria+Mall',
    ],
    amenities: {
      covered: false,
      evCharging: false,
      disabledAccess: false,
      cctv: true,
      valet: false,
      carWash: false,
    },
    hours: {
      is24Hours: false,
      openTime: '06:00',
      closeTime: '22:00',
      closedDays: [],
    },
    distanceMeters: 4800,
  },
  {
    id: 'lot-005',
    name: 'Red Sea Mall Parking',
    address: 'Prince Mohammad Bin Abdulaziz, Riyadh',
    location: { lat: 24.7156, lng: 46.6345 },
    totalSlots: 400,
    availableSlots: 92,
    pricePerHour: 14,
    pricePerDay: 55,
    rating: 4.6,
    reviewCount: 289,
    photoUrls: [
      'https://via.placeholder.com/400x300?text=Red+Sea+Mall',
    ],
    amenities: {
      covered: true,
      evCharging: true,
      disabledAccess: true,
      cctv: true,
      valet: false,
      carWash: true,
    },
    hours: {
      is24Hours: true,
      closedDays: [],
    },
    distanceMeters: 900,
  },
];
